- name: restart_nginx
  service: name=nginx state=restarted

- name: restart_supervisord
  service: name=supervisor state=restarted sleep=10
  ignore_errors: yes

- name: reread_config
  become: yes
  command: supervisorctl reread
  ignore_errors: yes

- name: update_supervisor
  become: yes
  command: supervisorctl reread
  ignore_errors: yes

- name: restart_app
  shell: supervisorctl restart {{ application_name }}
  ignore_errors: yes
